[package]
name = "rapid_python_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
crate-type = ["exe"]


[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
calamine = "0.18.0"